title: Tank Bible Reloaded
email: thelondoge@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

domain: thelondoge.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://thelondoge.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /tank-bible-reloaded      # place folder name if the site is served in a subfolder

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/